version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-west-2"
    GIT_IMAGE_REPO_NAME: "buildexample"
    AWS_IMAGE_REPO_NAME: "dnbi/scoring"
    IMAGE_TAG: "bexample100"
    AWS_ACCOUNT_ID: "236573294224"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $GIT_IMAGE_REPO_NAME:$IMAGE_TAG .
      # - docker build -t buildexample:be100 .
      - docker tag $GIT_IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker tag buildexample:be100 236573294224.dkr.ecr.us-west-2.amazonaws.com/dnbi/scoring:be100     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_REPO_NAME:$IMAGE_TAG
      # -  docker push 236573294224.dkr.ecr.us-west-2.amazonaws.com/dnbi/scoring:be100